#File Encryption - Write a program that uses a dictionary to assign “codes” to each letter of the alphabet. For example:

#codes = { ‘A’ : ‘%’, ‘a’ : ‘9’, ‘B’ : ‘@’, ‘b’ : ‘#’, etc . . .}

# Using this example, the letter A would be assigned the symbol %, 
# the letter a would be assigned the number 9, the letter B would be assigned the symbol @, 
# and so forth. The program should open a specified text file, read its contents, 
# then use the dictionary to write an encrypted version of the file’s contents to a second file. 
# Each character in the second file should contain the code for the corresponding character in the first file. 
# Use this text file to encrypt -

codes = {'A' : '!',
'a' : '@',
'B' : '#',
'b' : '$',
'C' : '%',
'c' : '^',
'D' : '&',
'd' : '*',
'E' : '(',
'e' : ')',
'F' : '-',
'f' : '_',
'G' : '+',
'g' : '=',
'H' : '|',
'h' : '\',
'I' : ']',
'i' : '[',
'J' : '{',
'j' : '}',
'K' : '?',
'k' : '/',
'L' : '>',
'l' : '.',
'M' : '<',
'm' : ',',
'N' : '`',
'n' : '~',
'O' : 'œ',
'o' : '∑',
'P' : '®',
'p' : '†',
'Q' : '¥',
'q' : '¨',
'R' : 'ˆ',
'r' : 'ø',
'S' : 'π',
's' : '£',
'T' : 'ß',
't' : '∂',
'U' : '™',
'u' : '©',
'V' : '˙',
'v' : '∆',
'W' : '˚',
'w' : '¬',
'X' : 'µ',
'x' : '˜',
'Y' : '∫', 
'y' : '√', 
'Z' : 'ç', 
'z' : '≈'}